### ISSUE TITLE
center aligned images not working

### ISSUE THREAD

**Issue by eilko** [flammy/imagebox#10]
When you center an image like 
`[{{ :artwork:jpeg-37.jpeg?nolink |Dessin pour un calendrier Le Petit Robert, en 1987}}]`

and the image is smaller than the with of the page, the image is aligned left with a correct box and text will flow on the right side. 

With the config option: "plugin imagebox center align" enabled, the box is full with, text will not flow on the right side but the image is still aligned  on the left, leaving blank space on the right.

**Comment by flammy** [comment]
I wrote a fix for this, please install my patched version:

https://github.com/flammy/imagebox/archive/flammy-patch-2.zip

If it works I will merge the fix into the next master release.

**Comment by eilko** [comment]
With the config option: "plugin imagebox center align" enabled the fix works. Without this option, nothing changes. Still a small issue:

See https://www.betaplana.be/en/testing

the first image is now aligned correctly. But if there is more caption, the box gets wider instead of wrapping the text. See the second and third image.

**Comment by flammy** [comment]
I made a fix for the caption.

IMHO the "center align" flag only allows to center imageboxes: if its not activated the image is aligned as: "not aligned". 

Please correct me, maybe I misunderstood the flag.

**Comment by eilko** [comment]
the caption is fixed. Thanks. I have no clue what the flag intention is. I have it now enabled. And imageboxes can be aligned right, left and center like normal images. 

Thanks for the help. You have fixed some of my last annoyances in Dokuwiki. Glad you took over the development of this plugin.

**Comment by flammy** [comment]
:smile:
