### ISSUE TITLE
Does not cooperate with "\\" any more

### ISSUE THREAD

**Issue by KaiMartin** [flammy/imagebox#108]
Imageboxes done with this plugin used to accept line breaks done by double backslashes "\\". 
I used this on several occasions to position text below rather than being squeezed next to the image.
Apparently, this does not work any more.  The double back slash is essentially ignored.

Is there a way to return to the previous behaviour?

Regards, 
---<)kaimartin(>---

PS: Thank you for maintaining this very useful plugin!

**Comment by KaiMartin** [comment]
Just found a work around: The Wrap plugin by Annika Henke provides the command
`<WRAP clear/>`
This seems to force any following text below the imageboxes.

**Comment by flammy** [comment]
Hey @KaiMartin,

I successfully testes the double slashes in the current version. 

You have to append a whitespace after the slashes:
`[{{wiki:dokuwiki-128.png|first line,\\ second line.}}]`
