### ISSUE TITLE
Make Image and Caption Linkable

### ISSUE THREAD

**Issue by justrob1980** [flammy/imagebox#123]
I am encountering an issue where I want to use Imagebox to include a caption for images. But I also want the image and the caption to be a clickable hyperlink to another page in the wiki. I have been experimenting with different permutations of combining the Imagebox syntax with the native Dokuwiki syntax for making images clickable links and it just doesn't work. 

Maybe I am missing something and this should work?

If not, is there any way to get a feature added to this plugin for this to be added to the native syntax of the plugin?

**Comment by flammy** [comment]
There is currently no way to link a whole box.

Dokuwiki encapsulates the content in an `a` element. This works fine if you use an `img` but we have to use a block element in this plugin to add the description.

You could prevent the img from beeing linked and put the link in the description:
`[{{  wiki:dokuwiki-128.png?nolink| Use [[wiki:hilfe|link]] in description}}]`
