### ISSUE TITLE
Update always showing up

### ISSUE THREAD

**Issue by Grandma-Betty** [flammy/imagebox#128]
I just updated to the latest version of imagebox but it still shows up as updateable.
Already tried to uninstall an re-install from scratch but that did not help.

![Unbenannt](https://github.com/flammy/imagebox/assets/48346793/4331bc4c-f1e9-4085-8b48-5923fdd1f3d3)

**Comment by raho0003** [comment]
@flammy Can you please update version numbering!

**Comment by flammy** [comment]
fixed.
