### ISSUE TITLE
Cannot achieve side-by-side images with "No align"

### ISSUE THREAD

**Issue by latchr** [flammy/imagebox#13]
I regularly want a set of images between two paragraphs, with the images sitting side-by-side. This is the default behaviour of Dokuwiki images (without imagebox), by simply putting multiple images with no blank line (paragraph break) between them. Eg:

{{:ns:image1.png?direct&200|caption1.}}
{{:ns:image1.png?direct&200|caption1.}}
{{:ns:image1.png?direct&200|caption1.}}

However, when I put [..] around these to get displayed captions, they shift to be one-image-per-line (undesired).

When I need one-image-per-line I can use centre align and it behaves as expected. Is there a way for me to get side-by-side images while using Imagebox?

I think it would be best if "no align" worked the same with imagebox as it does for default Dokuwiki images. This matches the typical user's expectations.

**Comment by flammy** [comment]
Hi @latchr sorry for my late answer.

I tried to reproduce your problem with the latest imagebox and the latest dokuwiki version:
```
At vero eos et accusam et justo duo dolores et ea rebum. gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. 


{{wiki:dokuwiki-128.png|caption1.}}
{{wiki:dokuwiki-128.png|caption1.}}
{{wiki:dokuwiki-128.png|caption1.}}


At vero eos et accusam et justo duo dolores et ea rebum. [[wiki:hilfe|Stet clita kasd]] gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.


[{{wiki:dokuwiki-128.png|caption1.}}]
[{{wiki:dokuwiki-128.png|caption1.}}]
[{{wiki:dokuwiki-128.png|caption1.}}]


At vero eos et accusam et justo duo dolores et ea rebum. [[wiki:hilfe|Stet clita kasd]] gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. 
```
Which results in:

![dw](https://user-images.githubusercontent.com/649155/32137264-d5675e52-bc1c-11e7-9c8b-87504e5b8fae.png)

 I see a problem there: the following paragraphs are floated behind the images - but this does not look like the problem you described.

**Comment by 0x46616c6b** [comment]
Hello,

i have the same problem and if i revert the commit 0269535c93b986d5dec352dd32f1d4ff32177b08 (remove `float: left`) the alignment works like expected.

Other option is to set `display: inline-block;` to `div.trien`.

**Comment by knurtz** [comment]
Hi,

I have the same problem.
```
[{{:image1.jpg?200|Caption1}}]
[{{:image2.jpg?200|Caption2}}]
[{{:image3.jpg?200|Caption3}}]
```
produces three pictures with each picture starting a new line. I manually added float:left to style.css as advised by 0x46616c6b but it showed no effect. Varying spaces before and after the image name only changes the alignment to left, middle or right, but pictures still start at a new line.
I am running Dokuwiki Release 2017-02-19e "Frusterick Manners" with imagebox version 2016-11-22.

**Comment by Rocreex** [comment]
Is there going to be an official fix? Is the `display: inline-block;` solution a proper fix or just a hack with side effects? Would you file a pull request?

**Comment by Dr-Yukon** [comment]
For compacting these images comment css-rule "clear:..." for div.tleft, div.tright and div.tcenter

**Comment by pluk77** [comment]
The following fork seems to have fixed this problem: https://github.com/CvH/imagebox

**Comment by flammy** [comment]
I have merged the Changes from @CvH and @Dr-Yukon, this should be fixed now.
