### ISSUE TITLE
Center caption below image

### ISSUE THREAD

**Issue by jackrubin** [flammy/imagebox#14]
Imagebox does a great job of centering the image but caption is always left justified. Please consider adding the option to center the caption under the image.

Thank you!

**Comment by flammy** [comment]
Hey @jackrubin,

Text alignment is not part of dokuwiki itself.

It can be achieved by the wrap plugin:

`[{{wiki:dokuwiki-128.png|<span center centeralign>center text</span>}}]`

**Comment by jackrubin** [comment]
Thanks, I’ve been playing with it a bit. I’ll dig deeper.
Jack
