### ISSUE TITLE
Responsive image resizing

### ISSUE THREAD

**Issue by flammy** [flammy/imagebox#3]
_Moved issues from dokuwiki comment section to github:_

It'd be nice if the use of imagebox didn't break responsive image functionality when using the default template in Detritus.

Version tested shows installed=Sat, 20 Dec 2014 11:46:58 +1100 in manager.dat

A crude hack allows this by changing:- 

`$renderer->doc.= '<div class="thumb2 t'.$match['align'].'" style="width:'.($match['w']?($match['w']+10).'px':'auto').'"><div class="thumbinner">';`

to

`$renderer->doc.= '<div class="thumb2 t'.$match['align'].'" style="width:100%"><div class="thumbinner">';`

Note: only tested using plugin»imagebox»display_magnify = if necessary, and plugin imagebox center align = on

**Comment by eilko** [comment]
Would be great if this could be fixed. The mentioned patch doesn't work fine as it often shows a large box around the image.

**Comment by flammy** [comment]
I have only copied the issue from dokuwiki.org

@eilko could you provide an example how this plugin breaks the responsive image layout?

**Comment by eilko** [comment]
I have made a test page: https://www.betaplana.be/en/testing

the original image is resized automatically by Dokuwiki to fit on the page and if you resize the browser window it gets smaller and still fits.

The boxed version looks weird as the box is way to wide. It also doesn't resize when you make you browser window smaller

**Comment by flammy** [comment]
Please install my patched version via the plugin-manager and check if the patch works for you:

https://github.com/flammy/imagebox/archive/flammy-patch-2.zip

**Comment by flammy** [comment]
This patch only fixes the responsive resize.  A redesign is needed to beautify the border.

**Comment by eilko** [comment]
I installed the patch and the image resizes! great! 

There are still some problems with the box itself though. See https://www.betaplana.be/en/testing
The box is too wide (height is perfect), is this also something you can fix?

**Comment by flammy** [comment]
Please reinstall the plugin from the above link, I made an update to the patch, where i fixed the alignment of the image in the box.

I just saw that you are using an image with a white left-and right-border on it, wich looks pretty weird.

The space between the border of your Artwork and the border of the imagebox is a blank area inside your image.

**Comment by eilko** [comment]
@flammy oops.. how could I have missed that :-( Thanks. I have reinstalled the patch and it works fine now. box looks great. Image resizes well. Thanks!!
